### ISSUE TITLE
Unable to run test model both in VM and in native

### ISSUE THREAD

**Issue by Tunahan-Uysal** [alphaparrot/ExoPlaSim#32]
When running the test model, it eventually ends up with it crashing around the same line with the following runtime warning.

This occurs both in VM and in native, the VM was an mx linux debian-based distro.

I have tried compiling it myself, apart from a red warning about 'armflang' which i assume I dont need due to my machine being x86, it succesfully compiled.

I have no clue what the issue with 'mpputgp' is, and this was occuring even before compilation.
I have also tried re-running the script after this, and it was the exact same to the line that the error occured.

I have also uploaded it as a file:
[error_exoplasim.log](https://github.com/user-attachments/files/16092516/error_exoplasim.log)
```
At line 798 of file plasim.f90
Fortran runtime warning: An array temporary was created for argument '_formal_183' of procedure 'mpputgp'
At line 799 of file plasim.f90
Fortran runtime warning: An array temporary was created for argument '_formal_183' of procedure 'mpputgp'
module 'scipy.integrate' has no attribute 'cumtrapz'
module 'scipy.integrate' has no attribute 'cumtrapz'
Error writing output to MOST.00000.nc; log written to postprocess.log
Going to stop here just in case......
mkdir: cannot create directory ‘/home/tunahan-uysal/exoplasim-scripts/testign12_crashed’: File exists
ExoPlaSim has crashed or begun producing garbage. All working files have been moved to /home/tunahan-uysal/exoplasim-scripts/testign12_crashed/
mkdir: cannot create directory ‘/home/tunahan-uysal/exoplasim-scripts/testign12_crashed’: File exists
mv: cannot stat '/home/tunahan-uysal/exoplasim-scripts/mymodel_testign12/*': No such file or directory
Traceback (most recent call last):
  File "/home/tunahan-uysal/.local/lib/python3.11/site-packages/exoplasim/__init__.py", line 1254, in postprocess
    pyburn.postprocess(inputfile,inputfile+self.extension,logfile=log,namelist=namelist,
  File "/home/tunahan-uysal/.local/lib/python3.11/site-packages/exoplasim/pyburn.py", line 3686, in postprocess
    data = dataset(rawfile, variables, mode=mode,radius=radius,gravity=gravity,gascon=gascon, 
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunahan-uysal/.local/lib/python3.11/site-packages/exoplasim/pyburn.py", line 1716, in dataset
    - scipy.integrate.cumtrapz(np.append([0,],
      ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'scipy.integrate' has no attribute 'cumtrapz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tunahan-uysal/.local/lib/python3.11/site-packages/exoplasim/__init__.py", line 1254, in postprocess
    pyburn.postprocess(inputfile,inputfile+self.extension,logfile=log,namelist=namelist,
  File "/home/tunahan-uysal/.local/lib/python3.11/site-packages/exoplasim/pyburn.py", line 3736, in postprocess
    data = dataset(rawfile, variables, mode=mode,radius=radius,gravity=gravity,gascon=gascon, 
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunahan-uysal/.local/lib/python3.11/site-packages/exoplasim/pyburn.py", line 1716, in dataset
    - scipy.integrate.cumtrapz(np.append([0,],
      ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'scipy.integrate' has no attribute 'cumtrapz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tunahan-uysal/.local/lib/python3.11/site-packages/exoplasim/__init__.py", line 959, in _run
    timeavg=self.postprocess(dataname,None,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunahan-uysal/.local/lib/python3.11/site-packages/exoplasim/__init__.py", line 1276, in postprocess
    if self.integritycheck("%s%s"%(inputfile,extension)):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunahan-uysal/.local/lib/python3.11/site-packages/exoplasim/__init__.py", line 1313, in integritycheck
    ioe = self.postprocess(ncfile[:-3],"example.nl",crashifbroken=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunahan-uysal/.local/lib/python3.11/site-packages/exoplasim/__init__.py", line 1286, in postprocess
    raise RuntimeError("Going to stop here just in case......")
RuntimeError: Going to stop here just in case......

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tunahan-uysal/.local/lib/python3.11/site-packages/exoplasim/__init__.py", line 973, in _run
    self._crash()
  File "/home/tunahan-uysal/.local/lib/python3.11/site-packages/exoplasim/__init__.py", line 1869, in _crash
    raise RuntimeError("ExoPlaSim has crashed or begun producing garbage. All working files have been moved to %s_crashed/"%(os.getcwd()+"/"+self.modelname))
RuntimeError: ExoPlaSim has crashed or begun producing garbage. All working files have been moved to /home/tunahan-uysal/exoplasim-scripts/testign12_crashed/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tunahan-uysal/exoplasim-scripts/first.py", line 4, in <module>
    mymodel.run(years=10,crashifbroken=True)
  File "/home/tunahan-uysal/.local/lib/python3.11/site-packages/exoplasim/__init__.py", line 495, in run
    self._run(**kwargs)
  File "/home/tunahan-uysal/.local/lib/python3.11/site-packages/exoplasim/__init__.py", line 1027, in _run
    self._crash() #Bring in the cleaners
    ^^^^^^^^^^^^^
  File "/home/tunahan-uysal/.local/lib/python3.11/site-packages/exoplasim/__init__.py", line 1869, in _crash
    raise RuntimeError("ExoPlaSim has crashed or begun producing garbage. All working files have been moved to %s_crashed/"%(os.getcwd()+"/"+self.modelname))
RuntimeError: ExoPlaSim has crashed or begun producing garbage. All working files have been moved to /home/tunahan-uysal/exoplasim-scripts/testign12_crashed/
```

**Comment by alphaparrot** [comment]
See https://github.com/alphaparrot/ExoPlaSim/issues/31; this is the same problem.
